// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxszlK88FGJ33oZhnMn6OYim3qQ6J6m7I',
    appId: '1:347978995200:web:5a2c4328ca0886956daae5',
    messagingSenderId: '347978995200',
    projectId: 'quizapp-d7a1a',
    authDomain: 'quizapp-d7a1a.firebaseapp.com',
    storageBucket: 'quizapp-d7a1a.firebasestorage.app',
    measurementId: 'G-DMF2DFCP2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAI0xduNMuzIbAEG3jDxIUJB0AJvONMuE',
    appId: '1:347978995200:android:186a45ab9b9473e16daae5',
    messagingSenderId: '347978995200',
    projectId: 'quizapp-d7a1a',
    storageBucket: 'quizapp-d7a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5fGM1v7Xj7wMmHOgKI6PhthwFpQZmxc',
    appId: '1:347978995200:ios:bd47b3640b35af506daae5',
    messagingSenderId: '347978995200',
    projectId: 'quizapp-d7a1a',
    storageBucket: 'quizapp-d7a1a.firebasestorage.app',
    iosClientId: '347978995200-0cmf3cjgdqu5mm8rlkrule5eqpbaotsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5fGM1v7Xj7wMmHOgKI6PhthwFpQZmxc',
    appId: '1:347978995200:ios:bd47b3640b35af506daae5',
    messagingSenderId: '347978995200',
    projectId: 'quizapp-d7a1a',
    storageBucket: 'quizapp-d7a1a.firebasestorage.app',
    iosClientId: '347978995200-0cmf3cjgdqu5mm8rlkrule5eqpbaotsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxszlK88FGJ33oZhnMn6OYim3qQ6J6m7I',
    appId: '1:347978995200:web:3f993ff0f4007aad6daae5',
    messagingSenderId: '347978995200',
    projectId: 'quizapp-d7a1a',
    authDomain: 'quizapp-d7a1a.firebaseapp.com',
    storageBucket: 'quizapp-d7a1a.firebasestorage.app',
    measurementId: 'G-JL4SBPKYJB',
  );
}